services:
  django:
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_SETTINGS_MODULE: config.settings.production

  fastapi:
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  nginx:
    restart: unless-stopped