# Generated by Django 5.1.4 on 2026-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('merged', 'Merged into another cart'), ('converted', 'Converted to order'), ('expired', 'Expired (abandoned)')], default='active', max_length=20),
        ),
    ]
